import Head from "next/head";
import Image from "next/image";
import NoteDisplay from "./components/NoteDisplay";
import NoteOperations from "./components/NoteOperations";
import styles from "../styles/Home.module.scss";
import { useState } from "react";

export default function Home() {
  const [mode, setMode] = useState(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <div className={styles.left}>
          <NoteOperations />
        </div>
        <div className={styles.right}>
          <span>
            <button onClick={() => setMode(!mode)} className={styles.modeButton}>{mode ? 'Dark Mode' : 'Light Mode'}</button>
          </span>
          <NoteDisplay mode={mode} />
        </div>
      </main>
    </>
  )
}
